name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Setup PHP
      id: setup-php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    
    - name: Install Dependencies
      run: composer install 

    - name: Rebuild Composer Autoload
      run: composer dump-autoload -o

    - name: Check File Existence
      run: |
        [ -f src/Plugin/NinjaForms/AdCaptchaField.php ] && echo "File exists: src/Plugin/NinjaForms/AdCaptchaField.php" || echo "File not found: src/Plugin/NinjaForms/AdCaptchaField.php"

    - name: Check Autoload
      run: |
        cat vendor/composer/autoload_psr4.php
        php -r "require 'vendor/autoload.php'; echo class_exists('AdCaptcha\\Plugin\\FluentForms\\Forms') ? 'Loaded' : 'Not Loaded';"

    - name: Run Tests
      run: composer test